spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/krim-resources-sytem?useSSL=false&amp;serverTimezone=UTC
    username: hbstudent
    password: hbstudent

